### ISSUE TITLE
Write to ecostream

### ISSUE THREAD

**Issue by michaeldoll** [rotflorg/node-red-contrib-ecoflow-powerstream#1]
Hello,
I have the following problem:
Reading from the ecostream works perfectly. But I can't get the write function to work.  I would like to set the value
write the value "setAcWatts". What does the json for this look like? Is there an example?

**Comment by rotflorg** [comment]
Hi, sorry for the late reply:

The message payload you need to send to the ecoflow-cmd should look like this (please insert correct serial number of your micro inverter):
`
    payload: {
        command: "setAcWatts",
        value: 200,
        deviceSn: "HW51ZXXXXXXXXXXX",
    }
`

And then, you need to send the output of the ecoflow-cmd to the MQTT output. The MQTT output should not have any topic configured. Hope this helps.

**Comment by rotflorg** [comment]
Closing issue, feel free to re-open or create another issue in case you run into trouble.
